"""Constructs the system prompt and parses LLM-generated questions."""
from __future__ import annotations

import warnings
from typing import Protocol


class LLMClient(Protocol):
    """Structural protocol for any LLM client that supports chat."""

    def chat(self, system_prompt: str, user_message: str, max_tokens: int = ...) -> str:
        ...


MAX_WORDS = 6000

SYSTEM_PROMPT_TEMPLATE = """\
You are a DevOps instructor assessing whether a student understands the homework solution they submitted.
The solution may have been generated by an AI assistant; your job is to produce questions that expose
whether the student has genuine understanding or merely copied output.

Generate exactly {question_count} questions about the solution below.
Rules:
- Number each question (1. 2. 3. ...), one per line, no blank lines between questions.
- No preamble, no postamble, no section headers — just the numbered list.
- Most questions should target constructs or patterns typical of AI-generated DevOps solutions
  (specific CLI flags, idiomatic YAML, library choices, networking concepts, security patterns, etc.)
  that a student who genuinely wrote the solution would explain without hesitation.
- At least one question per category: conceptual explanation, design rationale, counterfactual
  ("what if you removed X?"), edge case / failure mode, and alternative approach.
- Questions must go beyond re-reading the text; a student who skimmed it should not be able to answer.\
"""


def _truncate(text: str) -> str:
    words = text.split()
    if len(words) <= MAX_WORDS:
        return text
    return " ".join(words[:MAX_WORDS]) + "\n\n[NOTE: submission truncated for length]"


def generate_questions(
    client: LLMClient,
    solution_text: str,
    question_count: int = 12,
) -> list[str]:
    """Generate comprehension questions for a student's submission.

    The LLM client is passed in so this function is easily testable in isolation.
    """
    truncated = _truncate(solution_text)
    system_prompt = SYSTEM_PROMPT_TEMPLATE.format(question_count=question_count)
    raw = client.chat(system_prompt, truncated)

    if not raw.strip():
        raise ValueError("LLM returned an empty response — cannot generate questions.")

    questions: list[str] = []
    for line in raw.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        # Strip leading numbering: "1. ", "12. ", "1) ", etc.
        cleaned = stripped.lstrip("0123456789").lstrip(". )").strip()
        if cleaned:
            questions.append(cleaned)

    if not questions:
        raise ValueError("LLM response contained no parseable questions.")

    if len(questions) < question_count:
        warnings.warn(
            f"Requested {question_count} questions but only received {len(questions)}.",
            stacklevel=2,
        )

    return questions
